- hosts: container
  become: yes
  tasks:
    - name: upgrage packages
      apt:
        name: "*"
        state: latest
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes