- hosts: container
  tasks:
    - name: upgrage packages
      apt:
        upgrade: yes
        update_cache: yes
      become: true
      become_method: sudo
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: true
      become_method: sudo
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: true
      become_method: sudo
