version: 2
jobs:
  build-base-image:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build base iamge
          command: docker build -t base .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-base-image