version: 2
jobs:
  build-image:
    docker:
      - image: docker
    working_directory: ~/app
    environment:
      MY_IMAGE_NAME: test-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build my-ansible image
          command: docker build -f Dockerfile-ansible -t my-ansible .
      - run:
          name: build ansible for anyenv image
          command: docker build -f Dockerfile-anyenv -t my-ansible-anyenv .
      - run:
          name: build ansible for upgrade image
          command: docker build -f Dockerfile-upgrade -t my-ansible-upgrade .
      - run:
          name: build base iamge
          command: docker build -f Dockerfile-base -t my-base .
      - run:
          name: create network
          command: docker network create ansible
      - run:
          name: run my-base
          command: docker run -d --name base --net=ansible my-base
      - run:
          name: run ansible for anyenv
          command: docker run --rm --net=ansible my-ansible-anyenv
      - run:
          name: stop base
          command: docker stop base
      - run:
          name: commit image
          command: docker commit base base-anyenv
      - run:
          name: remove base
          command: docker rm base
      - run:
          name: run base
          command: docker run -d --name base --net=ansible base-anyenv
      - run:
          name: run ansible for upgrade
          command: docker run --rm --net=ansible my-ansible-upgrade
      - run:
          name: stop base
          command: docker stop base
      - run:
          name: commit image
          command: docker commit base result
      - run:
          name: rename image (vx.x.x)
          command: docker tag result $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG
      - run:
          name: docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: push image (vx.x.x)
          command: docker push $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG
  push-latest:
    docker:
      - image: docker
    working_directory: ~/app
    environment:
      MY_IMAGE_NAME: test-image
    steps:
      - setup_remote_docker
      - run:
          name: pull version
          command: echo "docker pull $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG"
      - run:
          name: set latest
          command: docker tag $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:latest
      - run:
          name: docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: push latest
          command: docker tag $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - HOLD-FRONT-BUILD:
          type: approval
          requires:
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - push-latest:
          requires:
            - HOLD-FRONT-BUILD
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
            