version: 2
jobs:
  build-base-image:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ssh config
          command: echo 'Host *' >> ~/.ssh/config && echo '  StrictHostKeyChecking no' >> ~/.ssh/config && echo '  UserKnownHostsFile=/dev/null' >> ~/.ssh/config && cat ~/.ssh/config
      - run:
          name: install ansible
          command: apk add --no-cache ansible
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build base iamge
          command: docker build -t base .
      - run:
          name: start base container
          command: docker run -d --name test -p 10022:22 base
      - run:
          name: ping
          command: ansible -i $(pwd)/hosts container --user cloud9 --private-key='$(pwd)/default.pem' -m ping
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-base-image
