version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - run:
          name: Greeting
          command: docker --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build