version: 2
jobs:
  build-base-image:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ssh config
          command: echo 'Host *' >> ~/.ssh/config && echo '  StrictHostKeyChecking no' >> ~/.ssh/config && echo '  UserKnownHostsFile=/dev/null' >> ~/.ssh/config && cat ~/.ssh/config
      - run:
          name: install ansible
          command: apk add --no-cache ansible
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build base iamge
          command: docker build -t base .
      - run:
          name: create network
          command: docker network create --subnet=192.168.56.0/24 my_network
      - run:
          name: start base container
          command: docker run -d --name test --net=my_network --ip=192.168.56.100 -p 10022:22 base
      - run:
          name: start base container
          command: apk add --no-cache openssh 
      - run:
          name: ping
          command: scp init.sh -i default.pem -P 10022 cloud9@192.168.56.100:~/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-base-image
