version: 2
jobs:
  build-base-image:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build ansible image
          command: docker build -f Dockerfile-ansible -t ansible .
      - run:
          name: build base iamge
          command: docker build -f Dockerfile-base -t base .
      - run:
          name: create network
          command: docker network create ansible
      - run:
          name: run base
          command: docker run -d --name base --net=ansible base
      - run:
          name: run ansible
          command: docker run --rm --net=ansible ansible

workflows:
  version: 2
  build:
    jobs:
      - build-base-image
