version: 2
jobs:
  build-base-image:
    docker:
      - image: docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install ansible
          command: apk add --no-cache ansible
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build base iamge
          command: docker build -t base .
      - run:
          name: check
          command: which ansible
      - run:
          name: start base container
          command: docker run -d -p 10022:22 base
      - run:
          name: ping
          command: ansible -i "localhost:10022," -u cloud9 -m ping
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-base-image
