version: 2
jobs:
  build-image:
    docker:
      - image: docker
    working_directory: ~/app
    environment:
      MY_IMAGE_NAME: test-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pull latest
          command: docker pull $DOCKERHUB_USERNAME/aws-cloud9-ubuntu
      - run:
          name: build ansible image
          command: docker build -f Dockerfile-ansible -t ansible .
      - run:
          name: build base iamge
          command: docker build -f Dockerfile-base -t base .
      - run:
          name: create network
          command: docker network create ansible
      - run:
          name: run base
          command: docker run -d --name base --net=ansible base
      - run:
          name: run ansible
          command: docker run --rm --net=ansible ansible
      - run:
          name: stop base
          command: docker stop base
      - run:
          name: commit image
          command: docker commit base result
      - run:
          name: docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: rename image (latest)
          command: docker tag result $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:latest
      - run:
          name: rename image (vx.x.x)
          command: docker tag result $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG
      - run:
          name: push image (latest)
          command: docker push $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:latest
      - run:
          name: push image (vx.x.x)
          command: docker push $DOCKERHUB_USERNAME/$MY_IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build-image:
      - build-test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
